#!/bin/sh
# cyclic srcdir srcfile dstdir app
#
# $1 = source directory
# $2 = source file name
# $3 = destination directory
# $4 = destination extension
#
echo $1
echo $2
echo $3
echo $4
if [ -f $1/$2 ]; then
  rm -f $3/6.$2$4
  if [ -f $3/5.$2$4 ]; then mv -f $3/5.$2$4 $3/6.$2$4; fi
  if [ -f $3/4.$2$4 ]; then mv -f $3/4.$2$4 $3/5.$2$4; fi
  if [ -f $3/3.$2$4 ]; then mv -f $3/3.$2$4 $3/4.$2$4; fi
  if [ -f $3/2.$2$4 ]; then mv -f $3/2.$2$4 $3/3.$2$4; fi
  if [ -f $3/1.$2$4 ]; then mv -f $3/1.$2$4 $3/2.$2$4; fi
  mv -f $1/$2 $3/1.$2$4
fi
